services:
  - type: web
    name: uk-weather-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        generateValue: true
